from pathlib import Path


def _normalize_server_url(raw_url: str) -> str:
    value = (raw_url or "").strip()
    if not value:
        return ""
    if not value.startswith(("http://", "https://")):
        value = f"http://{value}"
    return value.rstrip("/")


def _read_server_url(config_path: Path) -> str:
    if not config_path.exists():
        return ""

    for line in config_path.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        normalized = _normalize_server_url(text)
        if normalized:
            return normalized
    return ""


def main() -> int:
    base_dir = Path(__file__).resolve().parent
    source_file = base_dir / "server_url.txt"
    target_file = base_dir / "build_server_url.py"

    server_url = _read_server_url(source_file)
    if not server_url:
        print("[embed] 未在 server_url.txt 中读取到有效 URL")
        return 1

    target_file.write_text(
        "# Auto-generated by embed_server_url.py\n"
        "# Do not edit this file manually.\n"
        f"SERVER_URL = {server_url!r}\n",
        encoding="utf-8",
    )
    print(f"[embed] 已写入内嵌 URL: {server_url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
